### ISSUE TITLE
Release resource pack as standalone on Modrinth.

### ISSUE THREAD

**Issue by Patbox** [andre111/mambience#4]
Since Minecraft 1.20.3+ allows (custom) servers to apply multiple resource packs to the client, it might be beneficial to upload the required resource pack directly on modrinth. The download link could be then used as a resource pack url.

I'm asking for this, as I'm considering using this mod on my public server side modpack, but bundling the assets in main pack (or having it be rehosted on my side) doesn't sound as best approach.

**Comment by andre111** [comment]
Sorry for getting to this so late, but I manually uploaded the resourcepack for 5.5.1-1.21. Do you need any other versions?

**Comment by Patbox** [comment]
No need, as I uploaded them to my own web server for my own usage, but it will be nice for anyone else wanting to setup it.
